name: Build and Deploy Aswenna to the production
 
on:
  push:
    branches:
      - DEVELOPMENT
 
env:
  AZURE_WEBAPP_NAME: acciovac-prod-api
  DOTNET_VERSION: '10.0.x'
  IMAGE_NAME: aswenna-portal-frontend
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v4
 
      # - name: Setup .NET
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: ${{ env.DOTNET_VERSION }}
 
      # - name: Restore
      #   run: dotnet restore src/acciovac.API/acciovac.API.csproj
 
      # - name: Build
      #   run: dotnet build src/acciovac.API/acciovac.API.csproj -c Release --no-restore
 
      # 🔐 Login to ACR
      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
 
      # 🐳 Build & Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest \
            -f Dockerfile .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
 
      # 🚀 Deploy Container to Azure Web App
      - name: Deploy to Azure Web App (Container)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: |
            ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest